Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/? HTTP/1.1" 500 182854
Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/? HTTP/1.1" 500 182854
Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/ HTTP/1.1" 500 182822
Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/ HTTP/1.1" 500 182822
Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/ HTTP/1.1" 500 189005
Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/ HTTP/1.1" 500 189005
Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/ HTTP/1.1" 500 189005
Not Found: /dashboard/admin
"GET /dashboard/admin HTTP/1.1" 404 4326
